In [62]:
# importing the library
import tensorflow as tf
 
# initializing the constant tensor
a = tf.constant(value = [1,8,7,3,5,4,6,12],shape = (2,2,2))
 
# printing the initialized tensor
print(a, a.ndim)

tf.Tensor(
[[[ 1  8]
  [ 7  3]]

 [[ 5  4]
  [ 6 12]]], shape=(2, 2, 2), dtype=int32) 3


In [10]:
# getting the maximum value indices tensor
tf.math.argmax(a,0)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 3], dtype=int64)>

In [11]:
tf.argmax(a,1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 0, 0, 1], dtype=int64)>

In [12]:
tf.argmax(a,-1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 0, 0, 1], dtype=int64)>

In [14]:
import numpy as np
tf.random.set_seed(0)

data = np.arange(10).reshape(5, 2).astype(np.float32)
print(data)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [64]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor, rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
layer = tf.keras.layers.Dropout(.1, input_shape=(None,2))
outputs = layer(data, training=True)
print(outputs)

tf.Tensor(
[[ 0.         0.       ]
 [ 2.2222223  3.3333335]
 [ 4.4444447  5.555556 ]
 [ 6.666667   7.777778 ]
 [ 8.888889  10.       ]], shape=(5, 2), dtype=float32)


In [44]:
import tensorflow as tf
import numpy as np
input_shape = (2, 3, 4)
x = tf.random.normal(input_shape)
y = tf.keras.layers.GlobalAveragePooling1D()(x)
x, y

input_shape2 = (2, 5, 4, 3)
x2 = tf.random.normal(input_shape2)
y2 = tf.keras.layers.GlobalAveragePooling2D()(x2)
#x, y1, x2, y2

In [59]:
x = tf.constant([[1,2,4],[6,7,9]])
#tf.reshape(x, [-1]), 
tf.reshape(x,[-1]), x


(<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 4, 6, 7, 9])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 4],
        [6, 7, 9]])>)

In [69]:
B = tf.constant([1.7, -7.4])
C = tf.cast(B,dtype=tf.float16)
B,C, tf.abs(B)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 1.7, -7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1.7, -7.4], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>)

In [88]:
np.random.seed(12)
F = tf.constant(np.random.random(9),shape=(3,3))
F, tf.argmax(F)

(<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[0.15416284, 0.7400497 , 0.26331502],
        [0.53373939, 0.01457496, 0.91874701],
        [0.90071485, 0.03342143, 0.95694934]])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 0, 2], dtype=int64)>)

In [96]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
# print(function(x, y))

# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
    print('here..')
    return x ** 2 + y

tf_function(x, y), function(x, y)

here..


(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>)

In [100]:
!curl -O "https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  593k  100  593k    0     0   793k      0 --:--:-- --:--:-- --:--:--  793k


In [ ]:

len(i.split()